### ISSUE TITLE
zincSearch.document.create 方法报错，SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by cnn007** [IceHugh/zincsearch-node#1]
使用 zincSearch.document.create 创建单个document 时候 ，报错 SyntaxError: Unexpected end of JSON input
```js
async function create() {
  const result = await zincSearch.document.create({
    index: 'article',
    document: {
      title: '红楼梦',
      content: '红楼梦是四大名著',
      status: '红楼梦，名著',
    },
  })
  console.log(result)
}
```

errmsg:
```
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at consumeEnd (/Volumes/MacintoshHD2/workplace/Node/zincsearch-demo/node_modules/undici/lib/api/readable.js:258:20)
    at BodyReadable.<anonymous> (/Volumes/MacintoshHD2/workplace/Node/zincsearch-demo/node_modules/undici/lib/api/readable.js:240:7)
    at BodyReadable.emit (node:events:513:28)
    at BodyReadable.emit (/Volumes/MacintoshHD2/workplace/Node/zincsearch-demo/node_modules/undici/lib/api/readable.js:71:18)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
createOrUpdate 正常使用
```js
async function createOrUpdate() {
  const result = await zincSearch.document.createOrUpdate({
    id: '1682348859764',
    index: 'book',
    document: {
      title: '红楼梦3',
      content: '红楼梦是四大名著',
      status: '红楼梦，名著',
    },
  })
  console.log(result)
}
```
result:
```js
{
  message: 'ok',
  id: '1682348859764',
  _id: '1682348859764',
  _index: 'book',
  _version: 1,
  _seq_no: 0,
  _primary_term: 0,
  result: 'created'
}
```

**Comment by cnn007** [comment]
![image](https://user-images.githubusercontent.com/13449400/235064930-e727e1bd-b093-4416-8b43-94a6dab664fb.png)

**Comment by cnn007** [comment]
看了一下源码，创建方法path 多拼接了一个 '/'
